export default {
    "char": "String",
    "varchar": "String",
    "binary": "String",
    "tinyblob": "String",
    "tinytext": "String",
    "text": "String",
    "mediumtext": "String",
    "longtext": "String",
    "enum": "String",
    "set": "String",
    "date": "String",
    "datetime": "String",
    "timestamp": "String",
    "time": "String",
    "year": "String",
    "bit":"Number",
    "tinyint": "Number",
    "bool": "Number",
    "boolean": "Number",
    "smalint": "Number",
    "int": "Number",
    "integer": "Number",
    "bigint": "Number",
    "float": "Number",
    "double": "Number",
    "decimal": "Number",
    "dec": "Number"
}